#![allow(dead_code)]

use std::sync::atomic::{AtomicU16, Ordering};

use arbitrary::Arbitrary;
use semantic_decision_contracts::{
    ApplicabilityFact, ApplicabilityState, ArgumentKind, BoardPath, CanonicalCandidateId,
    CorrectionKind, DesignBelief, DesignFocus, DesignPosition, DesignStateId, DisclosureClass,
    FeedbackOption, FeedbackOptionKind, FiniteScore, FocusAbsenceReason, GameDomainId,
    GraphContentHash, GraphElementRef, GraphRevision, HistoryHash, LegalMove, LegalMoveId,
    MessageKey, MotifHypothesis, MoveArgument, MoveAttemptId, MoveAttemptOutcome,
    MoveAttemptReceipt, MoveProbability, ProducerIdentity, RuleCode, RuleExplanation,
    RuleExplanationId, SnapshotIdentity, UnresolvedDimension, GAMEBOARD_SCHEMA_VERSION,
};
use serde::{de::DeserializeOwned, Serialize};

static ATTEMPT_OUTCOME_COUNTERS: AtomicU16 = AtomicU16::new(0);
static DISCLOSURE_CLASS_COUNTERS: AtomicU16 = AtomicU16::new(0);

fn emit_once(counters: &AtomicU16, index: u8, category: &str, label: &str) {
    let bit = 1_u16 << index;
    if counters.fetch_or(bit, Ordering::Relaxed) & bit == 0 {
        eprintln!("semantic-counter {category}={label}");
    }
}

pub fn observe_attempt_outcome(receipt: &MoveAttemptReceipt) {
    let (index, label) = match receipt.outcome() {
        MoveAttemptOutcome::Applied => (0, "applied"),
        MoveAttemptOutcome::Incomplete => (1, "incomplete"),
        MoveAttemptOutcome::Ambiguous => (2, "ambiguous"),
        MoveAttemptOutcome::Inapplicable => (3, "inapplicable"),
        MoveAttemptOutcome::DisclosureSafeRefusal => (4, "disclosure_safe_refusal"),
        MoveAttemptOutcome::Stale => (5, "stale"),
        MoveAttemptOutcome::CompilerRefused => (6, "compiler_refused"),
        MoveAttemptOutcome::RejectedByUser => (7, "rejected_by_user"),
        MoveAttemptOutcome::Corrected => (8, "corrected"),
        MoveAttemptOutcome::SystemFailure => (9, "system_failure"),
    };
    emit_once(&ATTEMPT_OUTCOME_COUNTERS, index, "attempt_outcome", label);
}

pub fn observe_disclosure_class(disclosure: DisclosureClass) {
    let (index, label) = match disclosure {
        DisclosureClass::Public => (0, "public"),
        DisclosureClass::Authenticated => (1, "authenticated"),
        DisclosureClass::Restricted => (2, "restricted"),
        DisclosureClass::PolicyHidden => (3, "policy_hidden"),
        DisclosureClass::Technical => (4, "technical"),
    };
    emit_once(&DISCLOSURE_CLASS_COUNTERS, index, "disclosure_class", label);
}

#[derive(Debug)]
pub struct ContractTape<'a> {
    pub selector: u8,
    pub flags: u8,
    pub text: &'a [u8],
    pub count: u16,
}

impl<'a> Arbitrary<'a> for ContractTape<'a> {
    fn arbitrary(input: &mut arbitrary::Unstructured<'a>) -> arbitrary::Result<Self> {
        Ok(Self {
            selector: input.arbitrary()?,
            flags: input.arbitrary()?,
            count: input.arbitrary()?,
            text: input.peek_bytes(input.len()).unwrap_or_default(),
        })
    }

    fn size_hint(_depth: usize) -> (usize, Option<usize>) {
        (4, None)
    }
}

pub fn exercise_hostile_and_round_trip<T>(data: &[u8], generated: T)
where
    T: Serialize + DeserializeOwned + PartialEq + std::fmt::Debug,
{
    if let Ok(admitted) = serde_json::from_slice::<T>(data) {
        let canonical = serde_json::to_vec(&admitted).expect("admitted contract must encode");
        let rebuilt: T = serde_json::from_slice(&canonical).expect("canonical bytes must decode");
        assert_eq!(admitted, rebuilt);
        assert_eq!(canonical, serde_json::to_vec(&rebuilt).unwrap());
    }
    let canonical = serde_json::to_vec(&generated).expect("generated contract must encode");
    let rebuilt: T = serde_json::from_slice(&canonical).unwrap_or_else(|error| {
        panic!(
            "generated bytes must decode: {error}; packet={}",
            String::from_utf8_lossy(&canonical)
        )
    });
    assert_eq!(generated, rebuilt);
    assert_eq!(canonical, serde_json::to_vec(&rebuilt).unwrap());
}

fn text(tape: &ContractTape<'_>, fallback: &str) -> String {
    let value = String::from_utf8_lossy(tape.text)
        .chars()
        .filter(|character| !character.is_control())
        .take(32)
        .collect::<String>();
    if value.is_empty() {
        fallback.to_string()
    } else {
        value
    }
}

fn digest(seed: u8) -> String {
    format!("{seed:02x}").repeat(32)
}

pub fn graph_hash(seed: u8) -> GraphContentHash {
    GraphContentHash::new(digest(seed)).unwrap()
}

pub fn legal_move(tape: &ContractTape<'_>) -> LegalMove {
    let required = tape.flags & 1 != 0;
    let value = (!required).then_some(semantic_decision_contracts::SlotValue::Identifier(text(
        tape, "value",
    )));
    let provenance = value.as_ref().map(|_| "fuzz.explicit".to_string());
    let argument = MoveArgument::new(
        "argument",
        ArgumentKind::Identifier,
        required,
        value,
        provenance,
    )
    .unwrap();
    LegalMove::new(
        GAMEBOARD_SCHEMA_VERSION,
        CanonicalCandidateId::new(format!("candidate.{}", tape.selector)).unwrap(),
        GraphRevision::new("revision-fuzz").unwrap(),
        false,
        None,
        vec![argument],
        vec![ApplicabilityFact::new(
            RuleCode::new("rule.fuzz").unwrap(),
            ApplicabilityState::Applicable,
            None,
            "pack@fuzz",
        )
        .unwrap()],
        None,
    )
    .unwrap()
}

pub fn position(tape: &ContractTape<'_>) -> DesignPosition {
    let focus = match tape.selector % 4 {
        0 => DesignFocus::absent(FocusAbsenceReason::NotProvided, None).unwrap(),
        1 => DesignFocus::element(GraphElementRef::new(text(tape, "element")).unwrap()),
        2 => DesignFocus::subgraph(vec![
            GraphElementRef::new("element-a").unwrap(),
            GraphElementRef::new("element-b").unwrap(),
        ])
        .unwrap(),
        _ => DesignFocus::unknown(GraphElementRef::new(text(tape, "unknown")).unwrap()),
    };
    DesignPosition::new(
        GAMEBOARD_SCHEMA_VERSION,
        GameDomainId::new("domain.fuzz").unwrap(),
        BoardPath::new(vec!["root".into(), "bounded".into()]).unwrap(),
        SnapshotIdentity::new("snapshot-fuzz").unwrap(),
        GraphRevision::new("revision-fuzz").unwrap(),
        graph_hash(tape.flags),
        "compiler-fuzz",
        "policy-fuzz",
        None,
        focus,
        HistoryHash::new(digest(tape.selector)).unwrap(),
        vec![legal_move(tape)],
    )
    .unwrap()
}

pub fn outcome(selector: u8) -> MoveAttemptOutcome {
    match selector % 10 {
        0 => MoveAttemptOutcome::Applied,
        1 => MoveAttemptOutcome::Incomplete,
        2 => MoveAttemptOutcome::Ambiguous,
        3 => MoveAttemptOutcome::Inapplicable,
        4 => MoveAttemptOutcome::DisclosureSafeRefusal,
        5 => MoveAttemptOutcome::Stale,
        6 => MoveAttemptOutcome::CompilerRefused,
        7 => MoveAttemptOutcome::RejectedByUser,
        8 => MoveAttemptOutcome::Corrected,
        _ => MoveAttemptOutcome::SystemFailure,
    }
}

pub fn attempt(tape: &ContractTape<'_>) -> MoveAttemptReceipt {
    let outcome = outcome(tape.selector);
    let correction = (outcome == MoveAttemptOutcome::Corrected)
        .then(|| MoveAttemptId::new("original-attempt").unwrap());
    MoveAttemptReceipt::new(
        GAMEBOARD_SCHEMA_VERSION,
        MoveAttemptId::new(format!("attempt-{}", tape.selector)).unwrap(),
        DesignStateId::new(digest(1)).unwrap(),
        Some(LegalMoveId::new(digest(2)).unwrap()),
        graph_hash(3),
        outcome,
        vec![],
        vec![],
        correction,
        (outcome == MoveAttemptOutcome::Corrected).then_some(CorrectionKind::Replacement),
    )
    .unwrap()
}

pub fn disclosure(selector: u8) -> DisclosureClass {
    match selector % 5 {
        0 => DisclosureClass::Public,
        1 => DisclosureClass::Authenticated,
        2 => DisclosureClass::Restricted,
        3 => DisclosureClass::PolicyHidden,
        _ => DisclosureClass::Technical,
    }
}

pub fn explanation(tape: &ContractTape<'_>) -> RuleExplanation {
    RuleExplanation::new(
        GAMEBOARD_SCHEMA_VERSION,
        RuleCode::new(format!("rule.{}", tape.selector)).unwrap(),
        MessageKey::new("message.fuzz").unwrap(),
        vec![],
        "pack@fuzz",
        disclosure(tape.selector),
    )
    .unwrap()
}

pub fn feedback(tape: &ContractTape<'_>) -> FeedbackOption {
    let kinds = [
        FeedbackOptionKind::Retry,
        FeedbackOptionKind::SupplyArgument,
        FeedbackOptionKind::SelectAlternative,
        FeedbackOptionKind::ChangeFocus,
        FeedbackOptionKind::ChangeBoard,
        FeedbackOptionKind::ExplainRule,
        FeedbackOptionKind::Reject,
        FeedbackOptionKind::Undo,
        FeedbackOptionKind::Replace,
        FeedbackOptionKind::Escalate,
        FeedbackOptionKind::TechnicalRetry,
    ];
    FeedbackOption::new(
        kinds[usize::from(tape.selector) % kinds.len()],
        Some(LegalMoveId::new(digest(4)).unwrap()),
        MessageKey::new("feedback.fuzz").unwrap(),
        Some(RuleExplanationId::new(digest(5)).unwrap()),
        disclosure(tape.flags),
    )
}

pub fn belief(tape: &ContractTape<'_>) -> DesignBelief {
    DesignBelief::new(
        GAMEBOARD_SCHEMA_VERSION,
        DesignStateId::new(digest(6)).unwrap(),
        vec![MoveProbability::new(
            LegalMoveId::new(digest(7)).unwrap(),
            FiniteScore::new(f64::from(tape.selector) / 255.0).unwrap(),
        )
        .unwrap()],
        vec![MotifHypothesis::new(
            format!("motif.{}", tape.flags),
            FiniteScore::new(f64::from(tape.flags) / 255.0).unwrap(),
            "pack@fuzz",
        )
        .unwrap()],
        vec![UnresolvedDimension::new(
            "dimension.fuzz",
            vec!["option.a".into(), "option.b".into()],
        )
        .unwrap()],
        ProducerIdentity::new("producer-fuzz").unwrap(),
    )
    .unwrap()
}

/// Independent abstract invariant for the attempt tape. It deliberately knows
/// nothing about production hashing or serde implementation.
pub fn reference_attempt_is_valid(tape: &ContractTape<'_>, receipt: &MoveAttemptReceipt) {
    let expected = outcome(tape.selector);
    assert_eq!(receipt.outcome(), expected);
    assert_eq!(
        receipt.correction_of().is_some(),
        expected == MoveAttemptOutcome::Corrected
    );
}
